# Generated by Django 3.2.5 on 2021-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNum', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='studentUnion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unionName', models.CharField(max_length=20, verbose_name='社团名称')),
                ('unionNum', models.IntegerField(default=0, verbose_name='人数')),
            ],
            options={
                'db_table': 'student_union',
            },
        ),
    ]
