# Generated by Django 3.2.5 on 2021-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified'),
        ),
    ]
