# Generated by Django 3.2.5 on 2021-07-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210708_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='sort',
        ),
    ]
