# Generated by Django 3.2.5 on 2021-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_type_service_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='details',
            field=models.CharField(max_length=255, verbose_name='详细地址'),
        ),
    ]
