# Generated by Django 3.2.5 on 2021-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
