# Generated by Django 3.2.5 on 2021-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210710_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='评价'),
        ),
    ]
