# Generated by Django 3.2.5 on 2021-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_service_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='service',
            name='img2',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='服务图片位置'),
        ),
    ]
