# Generated by Django 3.2.5 on 2021-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_order_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='star',
            field=models.IntegerField(blank=True, null=True, verbose_name='店铺星级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='star',
            field=models.IntegerField(blank=True, null=True, verbose_name='服务星级'),
        ),
    ]
