# Generated by Django 3.2.5 on 2021-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='设置服务结束时间'),
        ),
        migrations.AddField(
            model_name='cart',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='设置服务开始时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(verbose_name='服务结束时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(verbose_name='服务开始时间'),
        ),
    ]
