# Generated by Django 3.2.5 on 2021-07-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210713_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_collection_id', models.CharField(max_length=32, unique=True, verbose_name='总订单号')),
            ],
            options={
                'db_table': 'OrderCollection',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_collection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ordercollection'),
        ),
    ]
