# Generated by Django 3.2.5 on 2021-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210713_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_collection_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OrderCollection'),
        ),
        migrations.DeleteModel(
            name='OrderCollection',
        ),
    ]
