# Generated by Django 3.2.5 on 2021-07-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210713_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name='订单支付状态'),
        ),
    ]
