# Generated by Django 3.2.5 on 2021-07-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_order_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_comment',
        ),
    ]
