# Generated by Django 3.2.5 on 2021-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_order_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='img2',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='该用户尚未评价,默认5星好评', max_length=255, null=True, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='star',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='服务星级'),
        ),
    ]
