# Generated by Django 3.2.5 on 2021-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_applyforshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='intro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务简介'),
        ),
    ]
